// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHYlH9t4vnIeEqzJV3aT0r0j-29RNr3Gs',
    appId: '1:867239061801:web:c6134e11e70c905854af38',
    messagingSenderId: '867239061801',
    projectId: 'mynotes-g',
    authDomain: 'mynotes-g.firebaseapp.com',
    storageBucket: 'mynotes-g.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEz-UY_Npl2YzCWte6Z4GHtyKgDkCaldU',
    appId: '1:867239061801:android:605b8f457cd920c454af38',
    messagingSenderId: '867239061801',
    projectId: 'mynotes-g',
    storageBucket: 'mynotes-g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmyRz_a9SN4uQfEG4RSKMwUIMrBrvn8A4',
    appId: '1:867239061801:ios:5f98f4b511309fad54af38',
    messagingSenderId: '867239061801',
    projectId: 'mynotes-g',
    storageBucket: 'mynotes-g.appspot.com',
    iosClientId: '867239061801-f44muih8052htv5fl2vi2a3rlf7299in.apps.googleusercontent.com',
    iosBundleId: 'com.mynotesg.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmyRz_a9SN4uQfEG4RSKMwUIMrBrvn8A4',
    appId: '1:867239061801:ios:5f98f4b511309fad54af38',
    messagingSenderId: '867239061801',
    projectId: 'mynotes-g',
    storageBucket: 'mynotes-g.appspot.com',
    iosClientId: '867239061801-f44muih8052htv5fl2vi2a3rlf7299in.apps.googleusercontent.com',
    iosBundleId: 'com.mynotesg.mynotes',
  );
}
